name: Send Daily Timetable

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  send-notification:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'   # ✅ Ye line change karo 3.10 se 3.13
    
    - name: Install dependencies
      run: |
        pip install pandas openpyxl requests
    
    - name: Run script
      run: python send_timetable.py
